recipes={
    "Honey Garlic Shrimp": ["shrimp", "honey", "soy sauce", "garlic", "ginger", "sesame oil", "green onions", "sesame seeds"],
    "Mushroom Risotto": ["arborio rice", "mushrooms", "vegetable broth", "onion", "white wine", "Parmesan cheese", "butter", "garlic", "thyme"],
    "Teriyaki Chicken": ["chicken thighs", "soy sauce", "mirin", "brown sugar", "garlic", "ginger", "cornstarch", "sesame seeds", "green onions", "sesame oil", "rice"],
    "Vegetable Paella": ["rice", "vegetable broth", "bell peppers", "tomatoes", "onion", "garlic", "green beans", "peas", "artichoke hearts", "saffron", "olive oil", "lemon"],
    "Homemade Pizza": ["pizza dough", "tomato sauce", "mozzarella cheese", "pepperoni", "bell peppers", "onion", "mushrooms", "olive oil", "Italian seasoning"],
    "Beef Tacos": ["ground beef", "taco seasoning", "taco shells", "lettuce", "tomatoes", "cheddar cheese", "sour cream", "salsa", "avocado"],
    "Pasta Primavera": ["pasta", "bell peppers", "zucchini", "yellow squash", "carrots", "broccoli", "tomatoes", "garlic", "olive oil", "Parmesan cheese"],
    "Butter Chicken": ["chicken thighs", "yogurt", "tomato sauce", "cream", "butter", "onion", "garlic", "ginger", "garam masala", "turmeric", "cumin", "coriander", "cayenne pepper", "lemon juice", "basmati rice", "naan bread"],
    "Beef and Broccoli": ["beef sirloin", "broccoli", "soy sauce", "brown sugar", "garlic", "ginger", "sesame oil", "cornstarch", "rice"],
    "Chicken Enchiladas": ["chicken breasts", "enchilada sauce", "flour tortillas", "cheddar cheese", "black beans", "corn", "green onions", "cilantro", "sour cream"],
    "Greek Salad": ["cucumbers", "tomatoes", "red onion", "Kalamata olives", "feta cheese", "olive oil", "lemon juice", "oregano", "salt", "pepper"],
    "Beef Wellington": ["beef tenderloin", "puff pastry", "mushrooms", "prosciutto", "Dijon mustard", "egg", "butter", "olive oil", "salt", "pepper"],
    "Chicken Fried Rice": ["cooked rice", "chicken breast", "peas", "carrots", "onion", "eggs", "soy sauce", "sesame oil", "garlic", "ginger"],
    "Spinach and Feta Stuffed Chicken": ["chicken breasts", "spinach", "feta cheese", "garlic", "lemon zest", "olive oil", "salt", "pepper"],
    "Ratatouille": ["eggplant", "zucchini", "yellow squash", "bell peppers", "tomatoes", "onion", "garlic", "olive oil", "thyme", "rosemary", "bay leaf"],
    "Beef Burritos": ["ground beef", "flour tortillas", "rice", "black beans", "cheddar cheese", "salsa", "sour cream", "avocado", "lettuce", "tomato"],
    "Tomato Basil Soup": ["tomatoes", "onion", "garlic", "vegetable broth", "cream", "basil", "olive oil", "salt", "pepper"],
    "Chicken Shawarma": ["chicken thighs", "yogurt", "lemon juice", "garlic", "cumin", "paprika", "turmeric", "cinnamon", "cayenne pepper", "olive oil", "pita bread", "tahini sauce", "cucumber", "tomato", "red onion"],
    "Pad Thai": ["rice noodles", "shrimp", "tofu", "bean sprouts", "green onions", "peanuts", "lime", "fish sauce", "tamarind paste", "brown sugar", "garlic", "eggs"],
    "Chicken Piccata": ["chicken breasts", "flour", "butter", "olive oil", "lemon", "chicken broth", "capers", "garlic", "parsley", "salt", "pepper"],
    "Vegetable Lasagna": ["lasagna noodles", "ricotta cheese", "mozzarella cheese", "Parmesan cheese", "spinach", "zucchini", "bell peppers", "onion", "garlic", "marinara sauce"],
    "Beef Kabobs": ["beef sirloin", "bell peppers", "red onion", "mushrooms", "zucchini", "olive oil", "garlic", "rosemary", "thyme", "salt", "pepper"],
    "Chicken Quesadillas": ["chicken breasts", "flour tortillas", "cheddar cheese", "bell peppers", "onion", "salsa", "sour cream", "guacamole"],
    "French Toast": ["bread", "eggs", "milk", "vanilla extract", "cinnamon", "butter", "maple syrup"],
    "Beef Gyros": ["beef sirloin", "pita bread", "tzatziki sauce", "tomato", "red onion", "lettuce", "cucumber", "olive oil", "lemon juice", "garlic", "oregano"],
    "Quinoa Salad": ["quinoa", "cucumber", "tomatoes", "red onion", "bell pepper", "black beans", "corn", "avocado", "cilantro", "lime", "olive oil", "salt", "pepper"],
    "Chicken Noodle Soup": ["chicken breasts", "chicken broth", "carrots", "celery", "onion", "garlic", "egg noodles", "thyme", "bay leaf", "parsley", "salt", "pepper"],
    "Pesto Pasta": ["pasta", "basil", "pine nuts", "Parmesan cheese", "garlic", "olive oil", "salt", "pepper"],
    "Stuffed Bell Peppers": ["bell peppers", "ground beef", "rice", "onion", "tomato sauce", "mozzarella cheese", "Parmesan cheese", "garlic", "Italian seasoning", "salt", "pepper"],
    "Hamburger": ["ground beef", "hamburger buns", "lettuce", "tomato", "onion", "pickles", "ketchup", "mustard", "mayonnaise", "cheese"],
    "Eggplant Parmesan": ["eggplant", "flour", "eggs", "breadcrumbs", "marinara sauce", "mozzarella cheese", "Parmesan cheese", "basil", "olive oil", "salt", "pepper"],
    "Lemon Herb Roast Pork": ["pork loin", "lemon", "garlic", "rosemary", "thyme", "olive oil", "salt", "pepper"],
    "Beef and Broccoli Stir Fry": ["beef sirloin", "broccoli", "soy sauce", "brown sugar", "garlic", "ginger", "sesame oil", "cornstarch", "rice"],
    "Chicken Caesar Salad": ["chicken breasts", "romaine lettuce", "Caesar dressing", "Parmesan cheese", "croutons"],
    "Vegetable Frittata": ["eggs", "milk", "bell peppers", "onion", "mushrooms", "spinach", "tomatoes", "cheddar cheese", "olive oil", "salt", "pepper"],
    "Mango Chicken Curry": ["chicken thighs", "mango", "coconut milk", "curry powder", "onion", "garlic", "ginger", "lime", "cilantro", "rice"],
    "Bruschetta": ["baguette", "tomatoes", "garlic", "basil", "olive oil", "balsamic vinegar", "salt", "pepper"],
    "Shrimp Fried Rice": ["cooked rice", "shrimp", "peas", "carrots", "onion", "eggs", "soy sauce", "sesame oil", "garlic", "ginger"],
    "Chicken Marsala": ["chicken breasts", "marsala wine", "mushrooms", "chicken broth", "butter", "flour", "olive oil", "garlic", "parsley", "salt", "pepper"],
    "Sushi Rolls": ["sushi rice", "seaweed sheets", "rice vinegar", "sugar", "salt", "fish (e.g., tuna, salmon)", "avocado", "cucumber", "carrots", "cream cheese", "soy sauce", "wasabi", "pickled ginger"],
    "Carnitas Tacos": ["pork shoulder", "orange", "lime", "garlic", "cumin", "oregano", "bay leaves", "tortillas", "salsa", "avocado", "cilantro", "onion"],
    "Ravioli with Tomato Sauce": ["ravioli", "tomato sauce", "Parmesan cheese", "basil"],
    "Beef Shepherd's Pie": ["ground beef", "onion", "carrots", "peas", "beef broth", "Worcestershire sauce", "garlic", "mashed potatoes", "butter", "salt", "pepper"],
    "Creamy Mushroom Soup": ["mushrooms", "onion", "garlic", "butter", "flour", "chicken broth", "cream", "thyme", "parsley", "salt", "pepper"],
    "BBQ Ribs": ["pork ribs", "BBQ sauce", "brown sugar", "paprika", "garlic powder", "onion powder", "salt", "pepper"],
    "Chicken Fajitas": ["chicken breasts", "bell peppers", "onion", "lime", "garlic", "chili powder", "cumin", "paprika", "salt", "pepper", "tortillas", "sour cream", "salsa", "guacamole"],
    "Cucumber Avocado Salad": ["cucumber", "avocado", "red onion", "cherry tomatoes", "feta cheese", "olive oil", "lemon juice", "salt", "pepper"],
    "Beef Enchiladas": ["ground beef", "enchilada sauce", "flour tortillas", "cheddar cheese", "black olives", "green onions", "sour cream"],
    "Goulash": ["beef stew meat", "onion", "bell peppers", "tomatoes", "beef broth", "paprika", "caraway seeds", "garlic", "bay leaf", "salt", "pepper"],
    "Pulled Chicken Sandwiches": ["chicken breasts", "BBQ sauce", "hamburger buns", "coleslaw"],
    "Potato Soup": ["potatoes", "bacon", "onion", "celery", "carrots", "garlic", "chicken broth", "milk", "flour", "butter", "cheddar cheese", "sour cream", "chives", "salt", "pepper"],
    "Tuna Salad": ["canned tuna", "mayonnaise", "celery", "red onion", "pickle relish", "lemon juice", "salt", "pepper"],

    "Lemon Herb Roast Chicken": ["whole chicken", "lemon", "garlic", "butter", "thyme", "rosemary", "salt", "pepper", "olive oil"],
    "Beef and Broccoli Stir-Fry": ["beef sirloin", "broccoli", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "cornstarch", "rice"],
    "Shrimp Scampi Pasta": ["shrimp", "linguine", "butter", "olive oil", "garlic", "lemon juice", "white wine", "parsley", "red pepper flakes", "salt", "pepper"],
    "Vegetarian Chili": ["black beans", "kidney beans", "bell peppers", "onion", "corn", "tomatoes", "tomato sauce", "chili powder", "cumin", "paprika", "garlic", "olive oil", "salt", "pepper"],
    "Spinach and Mushroom Quiche": ["pie crust", "spinach", "mushrooms", "onion", "eggs", "milk", "gruyere cheese", "salt", "pepper", "nutmeg"],
    "Lamb Gyros": ["lamb", "pita bread", "tzatziki sauce", "tomato", "red onion", "lettuce", "cucumber", "olive oil", "lemon juice", "garlic", "oregano"],
    "Chicken Teriyaki": ["chicken thighs", "soy sauce", "mirin", "brown sugar", "garlic", "ginger", "cornstarch", "sesame seeds", "green onions", "sesame oil", "rice"],
    "Butternut Squash Risotto": ["arborio rice", "butternut squash", "vegetable broth", "onion", "white wine", "Parmesan cheese", "butter", "garlic", "thyme"],
    "Vegetable Stir-Fry": ["mixed vegetables (e.g., bell peppers, broccoli, carrots)", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "cornstarch", "rice"],
    "Cauliflower Alfredo Pasta": ["cauliflower", "fettuccine", "butter", "garlic", "milk", "Parmesan cheese", "nutmeg", "salt", "pepper"],
    "Sesame Ginger Beef": ["beef sirloin", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "cornstarch", "green onions", "sesame seeds", "rice"],
    "Caprese Stuffed Chicken": ["chicken breasts", "mozzarella cheese", "tomato", "basil leaves", "balsamic vinegar", "olive oil", "salt", "pepper"],
    "Chicken and Rice Casserole": ["chicken breasts", "rice", "cream of chicken soup", "chicken broth", "onion", "garlic", "cheddar cheese", "salt", "pepper"],
    "Zucchini Noodles with Pesto": ["zucchini", "basil pesto", "cherry tomatoes", "Parmesan cheese", "pine nuts", "olive oil", "garlic", "salt", "pepper"],
    "Honey Mustard Glazed Salmon": ["salmon fillets", "honey", "Dijon mustard", "olive oil", "lemon juice", "garlic", "salt", "pepper"],
    "Mexican Stuffed Peppers": ["bell peppers", "ground beef", "rice", "black beans", "corn", "salsa", "cheddar cheese", "taco seasoning", "salt", "pepper"],
    "Cajun Shrimp Pasta": ["shrimp", "linguine", "Cajun seasoning", "butter", "olive oil", "garlic", "bell peppers", "onion", "cream", "Parmesan cheese", "parsley"],
    "Stuffed Chicken Breast": ["chicken breasts", "spinach", "sun-dried tomatoes", "mozzarella cheese", "garlic", "Italian seasoning", "salt", "pepper", "olive oil"],
    "Lentil Soup": ["lentils", "carrots", "celery", "onion", "garlic", "tomatoes", "vegetable broth", "bay leaf", "thyme", "parsley", "olive oil", "salt", "pepper"],
    "Thai Green Curry": ["chicken thighs", "Thai green curry paste", "coconut milk", "bell peppers", "zucchini", "bamboo shoots", "Thai basil", "lime leaves", "fish sauce", "brown sugar", "rice"],
    "Stuffed Portobello Mushrooms": ["portobello mushrooms", "spinach", "ricotta cheese", "Parmesan cheese", "garlic", "olive oil", "salt", "pepper"],
    "Moroccan Tagine": ["chicken thighs", "onion", "carrots", "potatoes", "tomatoes", "chickpeas", "apricots", "raisins", "chicken broth", "olive oil", "garlic", "ginger", "cinnamon", "cumin", "coriander", "turmeric", "cayenne pepper", "salt", "pepper"],
    "Greek Moussaka": ["eggplant", "potatoes", "ground beef", "onion", "tomatoes", "red wine", "cinnamon", "nutmeg", "olive oil", "butter", "flour", "milk", "Parmesan cheese", "egg", "salt", "pepper"],
    "Szechuan Chicken": ["chicken thighs", "soy sauce", "hoisin sauce", "rice vinegar", "brown sugar", "garlic", "ginger", "cornstarch", "chili flakes", "green onions", "sesame seeds", "rice"],
    "Salmon with Dill Sauce": ["salmon fillets", "lemon", "dill", "Greek yogurt", "garlic", "olive oil", "salt", "pepper"],
    "Vegetarian Bibimbap": ["rice", "tofu", "spinach", "carrots", "zucchini", "mushrooms", "bean sprouts", "eggs", "gochujang sauce", "sesame oil", "soy sauce", "garlic"],
    "Pumpkin Risotto": ["arborio rice", "pumpkin puree", "vegetable broth", "onion", "white wine", "Parmesan cheese", "butter", "garlic", "sage"],
    "Mediterranean Chicken": ["chicken breasts", "lemon", "olive oil", "garlic", "oregano", "thyme", "rosemary", "bell peppers", "red onion", "artichoke hearts", "Kalamata olives", "feta cheese"],
    "Black Bean and Sweet Potato Tacos": ["black beans", "sweet potatoes", "taco shells", "lettuce", "tomatoes", "avocado", "cilantro", "lime", "cumin", "chili powder", "garlic powder", "onion powder", "salt", "pepper"],
    "Eggplant Rollatini": ["eggplant", "ricotta cheese", "Parmesan cheese", "mozzarella cheese", "egg", "tomato sauce", "garlic", "olive oil", "basil", "oregano", "salt", "pepper"],
    "Beef and Cabbage Stir-Fry": ["beef sirloin", "cabbage", "carrots", "bell peppers", "onion", "garlic", "ginger", "soy sauce", "hoisin sauce", "sesame oil", "cornstarch", "rice"],
    "Crispy Tofu Stir-Fry": ["tofu", "bell peppers", "broccoli", "carrots", "snap peas", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "cornstarch", "rice"],
    "Chicken Pot Pie": ["chicken breasts", "pie crust", "carrots", "peas", "potatoes", "onion", "celery", "butter", "flour", "chicken broth", "milk", "thyme", "parsley", "salt", "pepper"],
    "Pasta Carbonara": ["spaghetti", "bacon", "eggs", "Parmesan cheese", "garlic", "olive oil", "parsley", "salt", "pepper"],
    "Sesame Garlic Noodles": ["spaghetti", "soy sauce", "sesame oil", "rice vinegar", "brown sugar", "garlic", "ginger", "cornstarch", "green onions", "sesame seeds"],
    "Vegetarian Chili Mac": ["macaroni", "black beans", "kidney beans", "bell peppers", "onion", "corn", "tomatoes", "tomato sauce", "chili powder", "cumin", "paprika", "garlic", "olive oil", "cheddar cheese", "salt", "pepper"],
    "Honey Garlic Glazed Pork Chops": ["pork chops", "honey", "soy sauce", "garlic", "ginger", "olive oil", "salt", "pepper"],
    "Creamy Mushroom Stroganoff": ["egg noodles", "mushrooms", "onion", "garlic", "sour cream", "Dijon mustard", "vegetable broth", "flour", "butter", "thyme", "parsley", "salt", "pepper"],
    "Sausage and Pepper Pasta": ["Italian sausage", "penne pasta", "bell peppers", "onion", "garlic", "tomato sauce", "crushed tomatoes", "Italian seasoning", "red pepper flakes", "olive oil", "salt", "pepper"],
    "Lentil Shepherd's Pie": ["green lentils", "onion", "carrots", "celery", "garlic", "vegetable broth", "tomato paste", "Worcestershire sauce", "thyme", "rosemary", "mashed potatoes", "butter", "milk", "salt", "pepper"],
    "Vegetable Biryani": ["basmati rice", "mixed vegetables (e.g., potatoes, carrots, peas)", "onion", "tomatoes", "yogurt", "ginger", "garlic", "green chilies", "mint leaves", "cilantro", "cumin", "coriander", "turmeric", "garam masala", "cardamom", "cloves", "cinnamon", "bay leaf", "cashews", "raisins", "ghee", "salt", "pepper"],
    "Sesame Ginger Tofu": ["tofu", "soy sauce", "sesame oil", "rice vinegar", "honey", "ginger", "garlic", "cornstarch", "sesame seeds", "green onions", "rice"],
    "Italian Wedding Soup": ["ground beef", "Italian sausage", "carrots", "celery", "onion", "garlic", "spinach", "chicken broth", "ditalini pasta", "Parmesan cheese", "egg", "parsley", "salt", "pepper"],
    "Vegetable Lo Mein": ["spaghetti", "mixed vegetables (e.g., bell peppers, broccoli, carrots)", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "green onions"],
    "Mushroom Wellington": ["portobello mushrooms", "puff pastry", "mushroom duxelles", "spinach", "shallots", "garlic", "olive oil", "thyme", "rosemary", "salt", "pepper"],
    "Lemon Garlic Shrimp Pasta": ["shrimp", "linguine", "butter", "olive oil", "garlic", "lemon juice", "white wine", "parsley", "red pepper flakes", "salt", "pepper"],
    "Sesame Tofu Buddha Bowl": ["tofu", "quinoa", "mixed greens", "carrots", "cucumber", "avocado", "edamame", "sesame seeds", "green onions", "sesame oil", "soy sauce", "rice vinegar", "garlic", "ginger"],
    "Coconut Curry Chicken": ["chicken thighs", "coconut milk", "curry powder", "onion", "bell peppers", "carrots", "potatoes", "garlic", "ginger", "lime", "cilantro", "rice"],
    "Stuffed Acorn Squash": ["acorn squash", "quinoa", "kale", "cranberries", "pecans", "feta cheese", "olive oil", "maple syrup", "balsamic vinegar", "garlic", "salt", "pepper"],
    "Vegetarian Enchiladas": ["black beans", "corn", "bell peppers", "onion", "jalapenos", "enchilada sauce", "flour tortillas", "cheddar cheese", "sour cream", "avocado", "cilantro"],
    "Teriyaki Tofu Stir-Fry": ["tofu", "bell peppers", "broccoli", "carrots", "snap peas", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "cornstarch", "rice"],
    "Tomato Basil Pasta": ["spaghetti", "tomatoes", "garlic", "olive oil", "fresh basil", "Parmesan cheese", "salt", "pepper"],
    "Vegetarian Stuffed Bell Peppers": ["bell peppers", "quinoa", "black beans", "corn", "onion", "tomatoes", "cheese", "enchilada sauce", "cilantro", "lime", "cumin", "chili powder", "salt", "pepper"],
    "Sesame Orange Chicken": ["chicken thighs", "orange juice", "soy sauce", "sesame oil", "brown sugar", "garlic", "ginger", "cornstarch", "orange zest", "sesame seeds", "green onions", "rice"],
    "Eggplant Lasagna": ["eggplant", "ricotta cheese", "mozzarella cheese", "Parmesan cheese", "marinara sauce", "basil", "oregano", "garlic", "olive oil", "salt", "pepper"],
    "Vegetable Curry": ["potatoes", "carrots", "bell peppers", "onion", "tomatoes", "coconut milk", "curry powder", "ginger", "garlic", "cilantro", "lime", "rice"],
    "Vegetarian Pad Thai": ["rice noodles", "tofu", "bean sprouts", "carrots", "bell peppers", "green onions", "peanuts", "lime", "soy sauce", "tamarind paste", "brown sugar", "garlic", "vegetable oil", "eggs"],
    "Baked Ziti": ["ziti pasta", "marinara sauce", "ricotta cheese", "mozzarella cheese", "Parmesan cheese", "fresh basil", "olive oil", "garlic", "salt", "pepper"],
    "Creamy Mushroom and Spinach Pasta": ["fettuccine", "mushrooms", "spinach", "garlic", "cream", "Parmesan cheese", "olive oil", "salt", "pepper"],
    "Vegan Sloppy Joes": ["lentils", "bell peppers", "onion", "garlic", "tomato sauce", "tomato paste", "brown sugar", "apple cider vinegar", "Worcestershire sauce", "chili powder", "paprika", "mustard powder", "salt", "pepper", "hamburger buns"],
    "Baked Salmon with Herbs": ["salmon fillets", "lemon", "dill", "parsley", "chives", "garlic", "olive oil", "salt", "pepper"],
    "Creamy Pumpkin Soup": ["pumpkin puree", "vegetable broth", "onion", "garlic", "heavy cream", "nutmeg", "cinnamon", "ginger", "butter", "olive oil", "salt", "pepper"],
    "Vegan Chickpea Curry": ["chickpeas", "coconut milk", "tomatoes", "onion", "garlic", "ginger", "curry powder", "cumin", "coriander", "turmeric", "cayenne pepper", "cilantro", "rice"],
    "Stuffed Cabbage Rolls": ["cabbage leaves", "ground beef", "rice", "onion", "garlic", "tomato sauce", "brown sugar", "lemon juice", "salt", "pepper"],
    "Veggie Burgers": ["black beans", "quinoa", "bell peppers", "onion", "breadcrumbs", "egg", "cumin", "chili powder", "garlic powder", "salt", "pepper", "hamburger buns", "lettuce", "tomato", "avocado", "mayonnaise", "mustard", "ketchup"],
    "Vegan Lentil Soup": ["green lentils", "carrots", "celery", "onion", "garlic", "tomatoes", "vegetable broth", "bay leaf", "thyme", "parsley", "olive oil", "salt", "pepper"],
    "Baked Stuffed Shells": ["jumbo pasta shells", "ricotta cheese", "mozzarella cheese", "Parmesan cheese", "marinara sauce", "spinach", "garlic", "olive oil", "salt", "pepper"],
    "Veggie Lo Mein": ["spaghetti", "mixed vegetables (e.g., bell peppers, broccoli, carrots)", "soy sauce", "hoisin sauce", "sesame oil", "garlic", "ginger", "green onions"],
    "Vegan Burrito Bowl": ["quinoa", "black beans", "corn", "bell peppers", "avocado", "salsa", "lime", "cumin", "chili powder", "garlic powder", "onion powder", "salt", "pepper", "cilantro"],
    "Mushroom Bourguignon": ["mushrooms", "onion", "carrots", "potatoes", "garlic", "red wine", "vegetable broth", "tomato paste", "flour", "thyme", "rosemary", "bay leaf", "olive oil", "salt", "pepper"],
    "Vegan Pad Thai": ["rice noodles", "tofu", "bean sprouts", "carrots", "bell peppers", "green onions", "peanuts", "lime", "soy sauce", "tamarind paste", "brown sugar", "garlic", "vegetable oil"],
    "Stuffed Zucchini Boats": ["zucchini", "ground turkey", "quinoa", "onion", "bell peppers", "tomatoes", "garlic", "Italian seasoning", "mozzarella cheese", "Parmesan cheese", "olive oil", "salt", "pepper"],
    "Vegan Lentil Shepherd's Pie": ["green lentils", "onion", "carrots", "celery", "garlic", "vegetable broth", "tomato paste", "Worcestershire sauce", "thyme", "rosemary", "mashed potatoes", "olive oil", "salt", "pepper"],

}
